### ISSUE TITLE
how to write code for delayed mailhopper

### ISSUE THREAD

**Issue by chaomao** [cerebris/delayed_mailhopper#2]
Hi guys, after some configuration follow read me, I want to ask you question about how to write code for delayed mailhopper?

I write these code for active mailer :
# define mailer class

class CandidateMailer < ActionMailer::Base
  default from: "xxx@gmail.com"

  def registration_confirmation(candidate)
    @candidate = candidate
    mail(:to => candidate.email, :subject => "xxx")
  end
end
# send email

CandidateMailer.registration_confirmation(candidate).deliver

and I wonder what kind of code do I need if I use delayed mailhopper?
Thanks for reply.

**Comment by dgeb** [comment]
Did you follow the Mailhopper configuration process too? You'll need to define mailhopper as the delivery method either for your whole app:

```
MyApp::Application.configure do
  config.action_mailer.delivery_method = :mailhopper
end
```

Or for individual mailers:

```
class MyMailer < ActionMailer::Base
  ActionMailer::Base.delivery_method = :mailhopper
end
```

For a working example see the test app in delayed_mailhopper/test/dummy. Here's its mailer class:
https://github.com/cerebris/delayed_mailhopper/blob/master/test/dummy/app/mailers/sample_mailer.rb

**Comment by chaomao** [comment]
Dan, I'm sorry I miss something. I have following config in my app. 

MyApp::Application.configure do
  config.action_mailer.delivery_method = :mailhopper
end

And I found that in my db, email table has a lot of data, but there is no data in delayed_jobs table. It seems that I miss some configuration for DelayedMailhopper.

**Comment by dgeb** [comment]
Sounds like a good start. Also,  DelayedMailhopper::Email needs to be configured as the email class for Mailhopper. This should be done by default (with no additional settings), so perhaps you're overriding it in your initializer?

You should be able to either remove this setting from your initializer or set it explicitly, like so:

```
Mailhopper::Base.setup do |config|
  # The base email class used by Mailhopper
  config.email_class =  DelayedMailhopper::Email
end
```

If that's set correctly, please let me know your version of ruby, rails, delayed_job and delayed_job_active_record so I can try to reproduce this problem.

**Comment by chaomao** [comment]
I have follow your suggestion and it works. Thanks so much, Dan.
Your guess was right, I have override  config.email_class = Mailhopper::Email in development.rb. It's total wrong.
After I recreate db and follow your steps, finally I got my email. Thanks Dan, thanks your awesome gem.

**Comment by dgeb** [comment]
You're quite welcome - glad it's working well for you now!
