### ISSUE TITLE
Is there any type of audit job?

### ISSUE THREAD

**Issue by brightball** [cerebris/delayed_mailhopper#4]
In the event that a delayed job queue gets locked up and somebody opts to clear the entire queue (it's happened before :-) is there a way to recreate delayed jobs for all unsent mail in the emails table?

**Comment by dgeb** [comment]
I'll put some thought into this - I can see how it would be useful. Thanks for the suggestion.

**Comment by brightball** [comment]
Cool, thanks.

**Comment by dgeb** [comment]
I added a "Troubleshooting" section to the README which covers how to regenerate jobs with a one-liner in the Rails console.
